apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-config
data:
  config.yaml: |
    # Review https://semgrep.dev/docs/semgrep-ci/network-broker for more instructions
    # This minimal example shows how to configure an optional allowlist and a GitHub Enterprise Server
    inbound:
      allowlist: [] # Optional. Empty list means all traffic outbound from the broker is permitted
    github:
      baseURL: https://GITHUB_BASE_URL/api/v3
      token: GITHUB_PAT
      allowCodeAccess: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: semgrep-network-broker
  name: semgrep-network-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semgrep-network-broker
  template:
    metadata:
      labels:
        app: semgrep-network-broker
    spec:
      containers:
      - name: broker
        image: ghcr.io/semgrep/semgrep-network-broker:v0.34.0
        args:
        - -c
        - /conf/config.yaml
        - -c
        - /private/private-key.yaml
        - --deployment-id
        - "YOUR_ORGANIZATION_ID" # UPDATE with your organization ID from https://semgrep.dev/orgs/-/settings/general/identifiers
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /conf
          name: config-volume
          readOnly: true
        - mountPath: /private
          name: private-key-volume
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: broker-config
      - name: private-key-volume
        secret:
          secretName: broker-private-key

# ---
# To create the kubernetes secret for the WireGuard private key, generate a file named private-key.yaml with the following contents:
#
#   inbound:
#     wireguard:
#       privateKey: WIREGUARD-PRIVATE-KEY-HERE
#
# Then create the Kubernetes secret with:
#
#   kubectl create secret generic broker-private-key-yaml --from-file=private-key.yaml
