apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-config
data:
  config.yaml: |
    # Review https://semgrep.dev/docs/semgrep-ci/network-broker for more instructions.
    # This minimal example shows how to configure an optional allowlist and a GitHub Enterprise Server.
    inbound:
      allowlist: [] # Optional. If unset, defaults to an empty array, permitting all outbound traffic from broker.
      github:
        baseURL: https://GHES_HOSTNAME/api/v3 # Update GHES_HOSTNAME to the domain of your GitHub server.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: semgrep-network-broker
  name: semgrep-network-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semgrep-network-broker
  template:
    metadata:
      labels:
        app: semgrep-network-broker
    spec:
      containers:
      - name: broker
        # Optionally replace :latest with desired tag version from https://github.com/semgrep/semgrep-network-broker/tags
        image: ghcr.io/semgrep/semgrep-network-broker:latest 
        args:
        - -c
        - /conf/config.yaml
        - -c
        - /secret/broker-secret.yaml
        - --deployment-id
        - "YOUR_ORGANIZATION_ID" # Update with your organization ID from https://semgrep.dev/orgs/-/settings/general/identifiers
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /conf
          name: config-volume
          readOnly: true
        - mountPath: /secret
          name: broker-secret-volume
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: broker-config
      - name: broker-secret-volume
        secret:
          secretName: broker-secret

# ---
# To create the kubernetes secret for the WireGuard private key, generate a file named broker-secret.yaml with the following contents:
#
#   inbound:
#     wireguard:
#       privateKey: WIREGUARD-PRIVATE-KEY-HERE
#
# Then create the Kubernetes secret with:
#
#   kubectl create secret generic broker-secret --from-file=broker-secret.yaml
# ---
