package main

import (
	"bytes"
	"fmt"
	"net/url"
	"os"
	"reflect"
	"regexp"
	"sort"
	"strings"

	"github.com/semgrep/semgrep-network-broker/pkg"
)

var (
	// Compile regexes once at package level
	startMarkerRe = regexp.MustCompile(`<!-- BeginAutogeneratedAllowList:([A-Za-z.]+) -->`)
	endMarkerRe   = regexp.MustCompile(`<!-- EndAutogeneratedAllowList:([A-Za-z.]+) -->`)
)

type urlInfo struct {
	Method string
	URL    string
}

// Create a set type for our URL/method pairs
type urlMethodSet map[string]struct{}

func makeSet(urls []urlInfo) urlMethodSet {
	set := make(urlMethodSet)
	for _, u := range urls {
		// Combine URL and method into a single string for the set
		key := fmt.Sprintf("%s %s", u.Method, u.URL)
		set[key] = struct{}{}
	}
	return set
}

func subtract(newSet, oldSet urlMethodSet) []urlInfo {
	var result []urlInfo
	for key := range newSet {
		if _, exists := oldSet[key]; !exists {
			// Split the key back into method and URL
			parts := strings.SplitN(key, " ", 2)
			result = append(result, urlInfo{
				Method: parts[0],
				URL:    parts[1],
			})
		}
	}
	return result
}

func extractUrlsFromAllowlist(allowlist pkg.Allowlist, baseURL *url.URL) ([]urlInfo, error) {
	methods := []struct {
		name string
		bit  uint
	}{
		{"GET", pkg.MethodGet},
		{"POST", pkg.MethodPost},
		{"PUT", pkg.MethodPut},
		{"PATCH", pkg.MethodPatch},
		{"DELETE", pkg.MethodDelete},
	}

	urls := []urlInfo{}
	for _, item := range allowlist {
		for _, m := range methods {
			if item.Methods.Test(m.bit) {
				urls = append(urls, urlInfo{
					Method: m.name,
					URL:    baseURL.JoinPath(item.URL).String(),
				})
			}
		}
	}

	// Sort URLs by HTTP method, then path for consistent output
	sort.Slice(urls, func(i, j int) bool {
		methodOrder := "GET,POST,PUT,PATCH,DELETE"
		iIndex := strings.Index(methodOrder, urls[i].Method)
		jIndex := strings.Index(methodOrder, urls[j].Method)
		if iIndex != jIndex {
			return iIndex < jIndex
		}
		return urls[i].URL < urls[j].URL
	})

	return urls, nil
}

func main() {
	readmePath := "../../README.md"
	content, err := os.ReadFile(readmePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading README.md: %v\n", err)
		os.Exit(1)
	}

	updates := make(map[string][]urlInfo)
	providers := []struct {
		name           string
		exampleBaseURL string
		config         *pkg.Config
	}{
		{"Github", "https://github.example.com", &pkg.Config{Inbound: pkg.InboundProxyConfig{GitHub: &pkg.GitHub{}}}},
		{"Gitlab", "https://gitlab.example.com", &pkg.Config{Inbound: pkg.InboundProxyConfig{GitLab: &pkg.GitLab{}}}},
		{"Bitbucket", "https://bitbucket.example.com", &pkg.Config{Inbound: pkg.InboundProxyConfig{BitBucket: &pkg.BitBucket{}}}},
		{"AzureDevOps", "https://dev.azure.com", &pkg.Config{Inbound: pkg.InboundProxyConfig{AzureDevOps: &pkg.AzureDevOps{}}}},
	}

	// Populate the allowlists for each provider
	for _, p := range providers {

		baseURL, err := url.Parse(p.exampleBaseURL)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to parse baseURL for %s: %v\n", p.name, err)
			os.Exit(1)
		}

		if err := pkg.PopulateAllowLists(p.config); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to populate allowlists for %s: %v\n", p.name, err)
			os.Exit(1)
		}

		// Populate with URLs which do not require code access
		standardUrls, err := extractUrlsFromAllowlist(p.config.Inbound.Allowlist, baseURL)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to extract URLs for %s: %v\n", p.name, err)
			os.Exit(1)
		}
		updates[p.name] = standardUrls

		if provider := reflect.ValueOf(p.config.Inbound).FieldByName(p.name); provider.IsValid() {
			provider.Elem().FieldByName("AllowCodeAccess").SetBool(true)
		}

		if err := pkg.PopulateAllowLists(p.config); err != nil {
			fmt.Fprintf(os.Stderr, "failed to populate allowlists for %s: %v\n", p.name, err)
			os.Exit(1)
		}

		urlsIncludingOnesRequiringCodeAccess, err := extractUrlsFromAllowlist(p.config.Inbound.Allowlist, baseURL)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to extract URLs for %s.AllowCodeAccess: %v\n", p.name, err)
			os.Exit(1)
		}

		// Populate exclusively with URLs requiring code access
		updates[p.name+".AllowCodeAccess"] = subtract(makeSet(urlsIncludingOnesRequiringCodeAccess), makeSet(standardUrls))
	}

	var buf bytes.Buffer
	lastIdx := 0

	// Replace URLs between "<!-- BeginAutogeneratedAllowList:... -->" and "<!-- EndAutogeneratedAllowList:... -->" tags
	for {
		startMatch := startMarkerRe.FindSubmatchIndex(content[lastIdx:])
		if startMatch == nil {
			break
		}

		startMatchEnd := lastIdx + startMatch[1]
		sectionName := string(content[lastIdx+startMatch[2] : lastIdx+startMatch[3]])

		endMatch := endMarkerRe.FindSubmatchIndex(content[startMatchEnd:])
		if endMatch == nil {
			fmt.Fprintf(os.Stderr, "no end marker found for section %s\n", sectionName)
			os.Exit(1)
		}

		buf.Write(content[lastIdx:startMatchEnd])
		buf.WriteByte('\n')

		if urls, ok := updates[sectionName]; ok {
			for _, u := range urls {
				fmt.Fprintf(&buf, "- %s `%s`\n", u.Method, u.URL)
			}
		}

		endMarkerStart := startMatchEnd + endMatch[0]
		lastIdx = startMatchEnd + endMatch[1]
		buf.Write(content[endMarkerStart:lastIdx])
	}

	buf.Write(content[lastIdx:])

	if err := os.WriteFile(readmePath, buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write README.md: %v\n", err)
		os.Exit(1)
	}
}
