package main

import (
	"bytes"
	"fmt"
	"net/url"
	"os"
	"regexp"
	"sort"
	"strings"

	"github.com/semgrep/semgrep-network-broker/pkg"
)

var (
	// Compile regexes once at package level
	startMarkerRe = regexp.MustCompile(`<!-- BeginAutogeneratedAllowList:([A-Za-z.]+) -->`)
	endMarkerRe   = regexp.MustCompile(`<!-- EndAutogeneratedAllowList:([A-Za-z.]+) -->`)
)

type urlInfo struct {
	Method string
	URL    string
}

// Order URLs by HTTP method, then path for consistent output
func sortUrls(urls []urlInfo) {
	methodOrder := map[string]int{
		"GET":    0,
		"POST":   1,
		"PUT":    2,
		"PATCH":  3,
		"DELETE": 4,
	}

	sort.Slice(urls, func(i, j int) bool {
		iOrder := methodOrder[urls[i].Method]
		jOrder := methodOrder[urls[j].Method]
		if iOrder != jOrder {
			return iOrder < jOrder
		}
		return urls[i].URL < urls[j].URL
	})
}

// Create a set type for our URL/method pairs
type urlMethodSet map[string]struct{}

func makeSet(urls []urlInfo) urlMethodSet {
	set := make(urlMethodSet)
	for _, u := range urls {
		// Combine URL and method into a single string for the set
		key := fmt.Sprintf("%s %s", u.Method, u.URL)
		set[key] = struct{}{}
	}
	return set
}

func subtract(newSet, oldSet urlMethodSet) []urlInfo {
	var result []urlInfo
	for key := range newSet {
		if _, exists := oldSet[key]; !exists {
			// Split the key back into method and URL
			parts := strings.SplitN(key, " ", 2)
			result = append(result, urlInfo{
				Method: parts[0],
				URL:    parts[1],
			})
		}
	}
	return result
}

func extractUrlsFromAllowlist(allowlist pkg.Allowlist, baseURL *url.URL) ([]urlInfo, error) {
	methods := []struct {
		name string
		bit  uint
	}{
		{"GET", pkg.MethodGet},
		{"POST", pkg.MethodPost},
		{"PUT", pkg.MethodPut},
		{"PATCH", pkg.MethodPatch},
		{"DELETE", pkg.MethodDelete},
	}

	urls := []urlInfo{}
	for _, item := range allowlist {
		for _, m := range methods {
			if item.Methods.Test(m.bit) {
				urls = append(urls, urlInfo{
					Method: m.name,
					URL:    baseURL.JoinPath(item.URL).String(),
				})
			}
		}
	}

	return urls, nil
}

const (
	GitHubProvider      = "Github"
	GitLabProvider      = "Gitlab"
	BitbucketProvider   = "Bitbucket"
	AzureDevOpsProvider = "AzureDevOps"
)

func main() {
	readmePath := "README.md"
	content, err := os.ReadFile(readmePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading README.md: %v\n", err)
		os.Exit(1)
	}

	updates := make(map[string][]urlInfo)
	providers := []struct {
		name           string
		exampleBaseURL string
		config         *pkg.Config
	}{
		{GitHubProvider, "https://github.example.com", &pkg.Config{Inbound: pkg.InboundProxyConfig{GitHub: &pkg.GitHub{}}}},
		{GitLabProvider, "https://gitlab.example.com", &pkg.Config{Inbound: pkg.InboundProxyConfig{GitLab: &pkg.GitLab{}}}},
		{BitbucketProvider, "https://bitbucket.example.com", &pkg.Config{Inbound: pkg.InboundProxyConfig{BitBucket: &pkg.BitBucket{}}}},
		{AzureDevOpsProvider, "https://dev.azure.com", &pkg.Config{Inbound: pkg.InboundProxyConfig{AzureDevOps: &pkg.AzureDevOps{}}}},
	}

	// Populate the allowlists for each provider
	for _, p := range providers {
		baseURL, err := url.Parse(p.exampleBaseURL)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to parse baseURL for %s: %v\n", p.name, err)
			os.Exit(1)
		}

		if err := pkg.PopulateAllowLists(p.config); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to populate allowlists for %s: %v\n", p.name, err)
			os.Exit(1)
		}

		urlsNotRequiringCodeAccess, err := extractUrlsFromAllowlist(p.config.Inbound.Allowlist, baseURL)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to extract URLs for %s: %v\n", p.name, err)
			os.Exit(1)
		}
		sortUrls(urlsNotRequiringCodeAccess)
		updates[p.name] = urlsNotRequiringCodeAccess

		switch p.name {
		case GitHubProvider:
			p.config.Inbound.GitHub.AllowCodeAccess = true
		case GitLabProvider:
			p.config.Inbound.GitLab.AllowCodeAccess = true
		case BitbucketProvider:
			p.config.Inbound.BitBucket.AllowCodeAccess = true
		case AzureDevOpsProvider:
			p.config.Inbound.AzureDevOps.AllowCodeAccess = true
		default:
			fmt.Fprintf(os.Stderr, "unhandled provider %s\n", p.name)
			os.Exit(1)
		}

		if err := pkg.PopulateAllowLists(p.config); err != nil {
			fmt.Fprintf(os.Stderr, "failed to populate allowlists for %s: %v\n", p.name, err)
			os.Exit(1)
		}

		allUrls, err := extractUrlsFromAllowlist(p.config.Inbound.Allowlist, baseURL)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to extract URLs for %s.AllowCodeAccess: %v\n", p.name, err)
			os.Exit(1)
		}

		urlsRequiringCodeAccess := subtract(makeSet(allUrls), makeSet(urlsNotRequiringCodeAccess))
		sortUrls(urlsRequiringCodeAccess)
		updates[p.name+".AllowCodeAccess"] = urlsRequiringCodeAccess
	}

	var buf bytes.Buffer
	lastIdx := 0

	// Replace URLs between "<!-- BeginAutogeneratedAllowList:... -->" and "<!-- EndAutogeneratedAllowList:... -->" tags
	for {
		startMatch := startMarkerRe.FindSubmatchIndex(content[lastIdx:])
		if startMatch == nil {
			break
		}

		startMatchEnd := lastIdx + startMatch[1]
		sectionName := string(content[lastIdx+startMatch[2] : lastIdx+startMatch[3]])

		endMatch := endMarkerRe.FindSubmatchIndex(content[startMatchEnd:])
		if endMatch == nil {
			fmt.Fprintf(os.Stderr, "no end marker found for section %s\n", sectionName)
			os.Exit(1)
		}

		buf.Write(content[lastIdx:startMatchEnd])
		buf.WriteByte('\n')

		if urls, ok := updates[sectionName]; ok {
			for _, u := range urls {
				fmt.Fprintf(&buf, "- %s `%s`\n", u.Method, u.URL)
			}
		}

		endMarkerStart := startMatchEnd + endMatch[0]
		lastIdx = startMatchEnd + endMatch[1]
		buf.Write(content[endMarkerStart:lastIdx])
	}

	buf.Write(content[lastIdx:])

	if err := os.WriteFile(readmePath, buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write README.md: %v\n", err)
		os.Exit(1)
	}
}
